import { GoogleGenAI, Type, Modality } from "@google/genai";
import type { TextAnalysisResult, ImageAnalysisResult, ImageTagsResult, WritingStyleProfile, DominantColorsResult } from '../types';

// Initializing Gemini API client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const safetySettings = [
    { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_NONE' },
    { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_NONE' },
    { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_NONE' },
    { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_NONE' },
];

/**
 * Helper to handle API rate limits (429) with exponential backoff
 */
async function generateWithRetry(fn: () => Promise<any>, maxRetries = 3): Promise<any> {
    let lastError: any;
    for (let i = 0; i < maxRetries; i++) {
        try {
            return await fn();
        } catch (error: any) {
            lastError = error;
            const isRateLimit = error?.message?.includes('429') || error?.message?.includes('quota') || error?.status === 429;
            if (isRateLimit && i < maxRetries - 1) {
                const delay = Math.pow(2, i) * 1000 + Math.random() * 1000;
                await new Promise(resolve => setTimeout(resolve, delay));
                continue;
            }
            throw error;
        }
    }
    throw lastError;
}

const textAnalysisSchema = {
  type: Type.OBJECT,
  properties: {
    aiLikelihood: {
      type: Type.NUMBER,
      description: 'A percentage likelihood (0-100) that the text was generated by AI.'
    },
    analysis: {
      type: Type.ARRAY,
      description: 'A breakdown of specific parts of the text.',
      items: {
        type: Type.OBJECT,
        properties: {
          originalText: {
            type: Type.STRING,
            description: 'The specific snippet of text being analyzed.'
          },
          reason: {
            type: Type.STRING,
            description: 'A granular explanation of why this snippet appears AI-generated.'
          },
          context: {
            type: Type.STRING,
            description: 'The broader context of the snippet.'
          },
          confidenceScore: {
            type: Type.NUMBER,
            description: 'A score from 0-100 indicating confidence.'
          },
          suggestions: {
            type: Type.ARRAY,
            description: 'Suggestions to make this snippet sound more human.',
            items: { type: Type.STRING }
          }
        },
        required: ['originalText', 'reason', 'context', 'suggestions', 'confidenceScore']
      }
    }
  },
  required: ['aiLikelihood', 'analysis']
};

export async function analyzeText(text: string): Promise<TextAnalysisResult> {
    const prompt = `
        You are a nuanced forensic AI text analyst. 
        
        **IMPORTANT PHILOSOPHY**: Do not be "overly critical." High-quality human writing is often formal, structured, and grammatically perfect. Do not penalize a user for being a good writer. 
        
        Only flag content as AI if you see:
        - Repetitive structural patterns (e.g., three sentences in a row starting with "By doing so...").
        - Excessive use of generic transitions (Moreover, Furthermore, In conclusion) that don't add value.
        - Circular logic or "hallucinatory" confidence where the text sounds certain but says nothing.
        - Lack of personal anecdote, specific cultural nuance, or "human messiness" (unusual but correct metaphors).

        **SCORING GUIDELINE**:
        - 0-30%: Human writing with standard clarity.
        - 30-60%: Polished writing that shares some structural traits with LLMs but lacks clear synthetic artifacts.
        - 70%+: Clear AI indicators (synthetic listicles, repetitive sentence cadence, specific LLM-signature phrasing).

        Perform the analysis in the original language of the text.
        
        Text to analyze:
        ---
        ${text}
        ---
    `;

    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: 'gemini-3-pro-preview',
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: textAnalysisSchema,
                temperature: 0.1,
                safetySettings,
            },
        });
        return JSON.parse(response.text);
    });
}

function mapToneToMode(tone?: string): string {
    if (!tone) return 'casual';
    const t = tone.toLowerCase();
    if (t.includes('professional') || t.includes('formal')) return 'professional';
    if (t.includes('bypass') || t.includes('stealth')) return 'bypass';
    if (t.includes('short') || t.includes('concise')) return 'shorten';
    if (t.includes('expand') || t.includes('detail')) return 'expand';
    return 'casual';
}

async function tryFlaskHumanize(text: string, mode: string): Promise<string | null> {
    try {
        const res = await fetch('/api/humanize', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ text, mode }),
        });
        if (!res.ok) return null;
        const data = await res.json();
        if (data.fallback || !data.humanized_text) return null;
        return data.humanized_text as string;
    } catch {
        return null;
    }
}

export async function humanizeText(text: string, styleProfile: WritingStyleProfile | null): Promise<string> {
    const mode = mapToneToMode(styleProfile?.tone);
    const flaskResult = await tryFlaskHumanize(text, mode);
    if (flaskResult) return flaskResult;

    let styleInstruction = `
        Focus on natural flow. Vary sentence lengths. Break up repetitive structures. 
        Inject subtle "human" imperfections like rhetorical questions or unique metaphors.
    `;

    if (styleProfile) {
        styleInstruction = `
            Adopt this style: "${styleProfile.description}". 
            Tone: ${styleProfile.tone}. Vocabulary: ${styleProfile.complexity}.
            Reference this sample: "${styleProfile.sample}"
        `;
    }

    const prompt = `
        Humanizer Engine. Transform the input into indistinguishable human writing.
        ${styleInstruction}
        Output ONLY the humanized text.
        
        Input:
        ---
        ${text}
        ---
    `;
    
    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: prompt,
            config: { temperature: 0.8, safetySettings },
        });
        return response.text.trim();
    });
}

export async function predictNextText(text: string, styleProfile: WritingStyleProfile | null): Promise<string> {
    const prompt = `Smart predictive text. Generate the next 1-2 sentences in a natural style. Input: "${text.substring(Math.max(0, text.length - 1000))}"`;
    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: prompt,
            config: { temperature: 0.7, safetySettings },
        });
        return response.text.trim();
    });
}

export async function improveText(text: string, style: string): Promise<string> {
    let instruction = '';
    switch (style) {
        case 'rephrase-gpt': instruction = `Rewrite the text. Provide 5 bulleted versions with different structures and tones.`; break;
        case 'reword': instruction = 'Reword while keeping the meaning identical.'; break;
        case 'shorten': instruction = 'Summarize and tighten the phrasing.'; break;
        case 'lengthen': instruction = 'Expand with more detail and descriptive language.'; break;
        case 'simplify': instruction = 'Use simpler vocabulary and shorter sentences.'; break;
        case 'readability': instruction = 'Organize for maximum clarity and ease of reading.'; break;
        case 'fix': default: instruction = 'Fix all spelling and grammar mistakes.'; break;
    }

    const prompt = `${instruction}\n\nText:\n${text}`;
    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: prompt,
            config: { temperature: 0.5, safetySettings },
        });
        return response.text.trim();
    });
}

export async function generateSpeech(text: string, voiceName: string = 'Zephyr'): Promise<string> {
    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-preview-tts",
            contents: [{ parts: [{ text }] }],
            config: {
                responseModalities: [Modality.AUDIO],
                speechConfig: {
                    voiceConfig: { prebuiltVoiceConfig: { voiceName } },
                },
            },
        });
        const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
        if (!base64Audio) throw new Error("TTS failed.");
        return base64Audio;
    });
}

export async function analyzeImage(base64Image: string, mimeType: string): Promise<ImageAnalysisResult> {
    const prompt = "Analyze this image for AI-generation markers. Provide aiLikelihood (0-100) and analysis feature list.";
    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: { parts: [{ text: prompt }, { inlineData: { data: base64Image, mimeType } }] },
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        aiLikelihood: { type: Type.NUMBER },
                        analysis: {
                            type: Type.ARRAY,
                            items: {
                                type: Type.OBJECT,
                                properties: {
                                    feature: { type: Type.STRING },
                                    reason: { type: Type.STRING },
                                    recommendation: { type: Type.STRING }
                                },
                                required: ['feature', 'reason', 'recommendation']
                            }
                        }
                    },
                    required: ['aiLikelihood', 'analysis']
                },
                temperature: 0.2,
                safetySettings,
            },
        });
        return JSON.parse(response.text);
    });
}

export async function describeImage(base64Image: string, mimeType: string): Promise<string> {
    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: { parts: [{ text: "Describe this image in detail." }, { inlineData: { data: base64Image, mimeType } }] },
            config: { temperature: 0.4, safetySettings },
        });
        return response.text.trim();
    });
}

export async function generateImageTags(base64Image: string, mimeType: string): Promise<ImageTagsResult> {
    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: { parts: [{ text: "Generate keywords for this image." }, { inlineData: { data: base64Image, mimeType } }] },
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        subjects: { type: Type.ARRAY, items: { type: Type.STRING } },
                        objects: { type: Type.ARRAY, items: { type: Type.STRING } },
                        setting: { type: Type.ARRAY, items: { type: Type.STRING } },
                        style: { type: Type.ARRAY, items: { type: Type.STRING } },
                        colors: { type: Type.ARRAY, items: { type: Type.STRING } },
                        composition: { type: Type.ARRAY, items: { type: Type.STRING } },
                    },
                    required: ['subjects', 'objects', 'setting', 'style', 'colors', 'composition']
                },
                temperature: 0.3,
                safetySettings,
            },
        });
        return JSON.parse(response.text);
    });
}

export async function getDominantColors(base64Image: string, mimeType: string): Promise<DominantColorsResult> {
    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: { parts: [{ text: "Extract top 5 colors." }, { inlineData: { data: base64Image, mimeType } }] },
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        colors: {
                            type: Type.ARRAY,
                            items: {
                                type: Type.OBJECT,
                                properties: {
                                    hex: { type: Type.STRING },
                                    name: { type: Type.STRING },
                                    percentage: { type: Type.NUMBER }
                                }
                            }
                        }
                    }
                },
                temperature: 0.2,
                safetySettings,
            },
        });
        return JSON.parse(response.text);
    });
}

export async function editImage(base64Image: string, mimeType: string, prompt: string, ref64?: string, refMime?: string): Promise<string> {
    const parts: any[] = [{ inlineData: { data: base64Image, mimeType } }];
    if (ref64 && refMime) parts.push({ inlineData: { data: ref64, mimeType: refMime } });
    parts.push({ text: `${prompt} - Blend naturally.` });

    return generateWithRetry(async () => {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: { parts },
            config: { temperature: 0.5, safetySettings },
        });
        const part = response.candidates?.[0]?.content?.parts?.find((p: any) => p.inlineData);
        if (part) return part.inlineData.data;
        throw new Error("Edit failed.");
    });
}
