// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hayle-image/ImageAccessibility.tsx": () => import("../components/mockups/hayle-image/ImageAccessibility.tsx"),
  "./components/mockups/hayle-image/ImageAffordance.tsx": () => import("../components/mockups/hayle-image/ImageAffordance.tsx"),
  "./components/mockups/hayle-image/ImageHierarchy.tsx": () => import("../components/mockups/hayle-image/ImageHierarchy.tsx"),
  "./components/mockups/hayle-usability/AccessibilityReadability.tsx": () => import("../components/mockups/hayle-usability/AccessibilityReadability.tsx"),
  "./components/mockups/hayle-usability/AffordanceVisibility.tsx": () => import("../components/mockups/hayle-usability/AffordanceVisibility.tsx"),
  "./components/mockups/hayle-usability/HierarchyClarity.tsx": () => import("../components/mockups/hayle-usability/HierarchyClarity.tsx")
};
